package com.example.model

data class BrazilianStock(
    val symbol: String, // e.g., "BMFBOVESPA:PETR4"
    val ticker: String, // e.g., "PETR4"
    val name: String,   // e.g., "Petrobras PN"
    val sector: String, // e.g., "Petróleo & Gás"
    val isIndexOrCurrency: Boolean = false,
    val description: String = "",
    val price: String = "R$ 38,90",
    val changePercent: String = "+1.45%",
    val isPositive: Boolean = true,
    val changeValue: String = "+R$ 0,55",
    val dailyHigh: String = "R$ 39,20",
    val dailyLow: String = "R$ 38,15",
    val volume: String = "48,2M",
    val marketCap: String = "R$ 498B",
    val peRatio: String = "4.2x",
    val dividendYield: String = "14.8%",
    val high52w: String = "R$ 42,50",
    val low52w: String = "R$ 29,80"
)

object BrazilMarketData {
    val benchmarkIndices = listOf(
        BrazilianStock(
            symbol = "BMFBOVESPA:IBOV",
            ticker = "IBOV",
            name = "Índice Ibovespa",
            sector = "Benchmark B3",
            isIndexOrCurrency = true,
            description = "Principal indicador do desempenho médio das cotações dos ativos de maior negociabilidade e representatividade da B3.",
            price = "134.250 pts",
            changePercent = "+0.85%",
            isPositive = true,
            changeValue = "+1.130 pts",
            dailyHigh = "134.890",
            dailyLow = "133.120",
            volume = "R$ 22,4B",
            marketCap = "R$ 4,8T",
            peRatio = "8.1x",
            dividendYield = "6.2%",
            high52w = "137.469 pts",
            low52w = "118.160 pts"
        ),
        BrazilianStock(
            symbol = "FX_IDC:USDBRL",
            ticker = "USD/BRL",
            name = "Dólar Comercial",
            sector = "Forex / Câmbio",
            isIndexOrCurrency = true,
            description = "Taxa de câmbio Dólar Americano em relação ao Real Brasileiro.",
            price = "R$ 5,4230",
            changePercent = "-0.32%",
            isPositive = false,
            changeValue = "-R$ 0,0174",
            dailyHigh = "R$ 5,4610",
            dailyLow = "R$ 5,4180",
            volume = "US$ 18,2B",
            marketCap = "-",
            peRatio = "-",
            dividendYield = "-",
            high52w = "R$ 5,8600",
            low52w = "R$ 4,8500"
        ),
        BrazilianStock(
            symbol = "FX_IDC:EURBRL",
            ticker = "EUR/BRL",
            name = "Euro / Real",
            sector = "Forex / Câmbio",
            isIndexOrCurrency = true,
            description = "Taxa de câmbio da moeda única européia em Reais.",
            price = "R$ 6,0410",
            changePercent = "-0.15%",
            isPositive = false,
            changeValue = "-R$ 0,0090",
            dailyHigh = "R$ 6,0720",
            dailyLow = "R$ 6,0310",
            volume = "€ 4,1B",
            marketCap = "-",
            peRatio = "-",
            dividendYield = "-",
            high52w = "R$ 6,3500",
            low52w = "R$ 5,2800"
        )
    )

    val topStocks = listOf(
        BrazilianStock(
            symbol = "BMFBOVESPA:PETR4",
            ticker = "PETR4",
            name = "Petrobras PN",
            sector = "Petróleo & Gás",
            description = "Petróleo Brasileiro S.A., gigante estatal e líder mundial em exploração em águas ultraprofundas no pré-sal.",
            price = "R$ 38,90",
            changePercent = "+1.45%",
            isPositive = true,
            changeValue = "+R$ 0,55",
            dailyHigh = "R$ 39,25",
            dailyLow = "R$ 38,10",
            volume = "54,2M",
            marketCap = "R$ 507B",
            peRatio = "4.2x",
            dividendYield = "14.8%",
            high52w = "R$ 42,90",
            low52w = "R$ 30,10"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:VALE3",
            ticker = "VALE3",
            name = "Vale ON",
            sector = "Mineração & Metais",
            description = "Uma das maiores mineradoras globais, líder mundial na produção de minério de ferro, pelotas e níquel.",
            price = "R$ 59,20",
            changePercent = "-0.80%",
            isPositive = false,
            changeValue = "-R$ 0,48",
            dailyHigh = "R$ 60,10",
            dailyLow = "R$ 58,95",
            volume = "32,8M",
            marketCap = "R$ 265B",
            peRatio = "5.6x",
            dividendYield = "8.4%",
            high52w = "R$ 77,20",
            low52w = "R$ 54,80"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:ITUB4",
            ticker = "ITUB4",
            name = "Itaú Unibanco PN",
            sector = "Serviços Financeiros",
            description = "Maior conglomerado financeiro privado da América Latina e do hemisfério sul.",
            price = "R$ 35,40",
            changePercent = "+0.65%",
            isPositive = true,
            changeValue = "+R$ 0,23",
            dailyHigh = "R$ 35,65",
            dailyLow = "R$ 35,10",
            volume = "26,1M",
            marketCap = "R$ 342B",
            peRatio = "8.9x",
            dividendYield = "6.9%",
            high52w = "R$ 36,80",
            low52w = "R$ 26,40"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:BBDC4",
            ticker = "BBDC4",
            name = "Banco Bradesco PN",
            sector = "Serviços Financeiros",
            description = "Segundo maior banco privado brasileiro, presente em todo o território nacional.",
            price = "R$ 15,10",
            changePercent = "+0.40%",
            isPositive = true,
            changeValue = "+R$ 0,06",
            dailyHigh = "R$ 15,30",
            dailyLow = "R$ 14,95",
            volume = "38,5M",
            marketCap = "R$ 152B",
            peRatio = "9.4x",
            dividendYield = "7.5%",
            high52w = "R$ 17,40",
            low52w = "R$ 12,20"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:BBAS3",
            ticker = "BBAS3",
            name = "Banco do Brasil ON",
            sector = "Serviços Financeiros",
            description = "Instituição financeira mais antiga do Brasil, líder nacional em crédito ao agronegócio.",
            price = "R$ 28,30",
            changePercent = "+0.90%",
            isPositive = true,
            changeValue = "+R$ 0,25",
            dailyHigh = "R$ 28,55",
            dailyLow = "R$ 28,05",
            volume = "21,4M",
            marketCap = "R$ 161B",
            peRatio = "4.4x",
            dividendYield = "10.2%",
            high52w = "R$ 29,90",
            low52w = "R$ 22,10"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:ABEV3",
            ticker = "ABEV3",
            name = "Ambev ON",
            sector = "Bebidas & Consumo",
            description = "Subsidiária da Anheuser-Busch InBev, maior cervejaria da América Latina e dona de marcas icônicas.",
            price = "R$ 12,85",
            changePercent = "-0.15%",
            isPositive = false,
            changeValue = "-R$ 0,02",
            dailyHigh = "R$ 13,00",
            dailyLow = "R$ 12,78",
            volume = "19,2M",
            marketCap = "R$ 202B",
            peRatio = "13.2x",
            dividendYield = "6.1%",
            high52w = "R$ 15,30",
            low52w = "R$ 11,20"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:WEGE3",
            ticker = "WEGE3",
            name = "WEG ON",
            sector = "Bens de Capital & Motores",
            description = "Multinacional brasileira de motores elétricos, automação industrial, geradores e transição energética.",
            price = "R$ 54,10",
            changePercent = "+2.10%",
            isPositive = true,
            changeValue = "+R$ 1,11",
            dailyHigh = "R$ 54,60",
            dailyLow = "R$ 53,20",
            volume = "14,8M",
            marketCap = "R$ 227B",
            peRatio = "34.5x",
            dividendYield = "1.8%",
            high52w = "R$ 56,10",
            low52w = "R$ 32,50"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:RENT3",
            ticker = "RENT3",
            name = "Localiza ON",
            sector = "Locação de Veículos",
            description = "Líder sul-americana no aluguel e gestão de frotas automotivas após fusão histórica com a Unidas.",
            price = "R$ 44,70",
            changePercent = "-1.20%",
            isPositive = false,
            changeValue = "-R$ 0,54",
            dailyHigh = "R$ 45,50",
            dailyLow = "R$ 44,20",
            volume = "11,2M",
            marketCap = "R$ 47B",
            peRatio = "16.1x",
            dividendYield = "4.2%",
            high52w = "R$ 64,80",
            low52w = "R$ 41,50"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:B3SA3",
            ticker = "B3SA3",
            name = "B3 ON",
            sector = "Infraestrutura Financeira",
            description = "Brasil, Bolsa, Balcão - única bolsa de valores oficial em funcionamento contínuo no Brasil.",
            price = "R$ 11,60",
            changePercent = "+0.35%",
            isPositive = true,
            changeValue = "+R$ 0,04",
            dailyHigh = "R$ 11,75",
            dailyLow = "R$ 11,48",
            volume = "34,9M",
            marketCap = "R$ 63B",
            peRatio = "14.8x",
            dividendYield = "5.8%",
            high52w = "R$ 14,90",
            low52w = "R$ 10,40"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:SUZB3",
            ticker = "SUZB3",
            name = "Suzano ON",
            sector = "Papel & Celulose",
            description = "Maior produtora global de celulose de eucalipto e pioneira em biomateriais sustentáveis.",
            price = "R$ 57,80",
            changePercent = "+0.70%",
            isPositive = true,
            changeValue = "+R$ 0,40",
            dailyHigh = "R$ 58,40",
            dailyLow = "R$ 57,10",
            volume = "8,4M",
            marketCap = "R$ 74B",
            peRatio = "7.2x",
            dividendYield = "3.5%",
            high52w = "R$ 62,40",
            low52w = "R$ 46,20"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:JBSS3",
            ticker = "JBSS3",
            name = "JBS ON",
            sector = "Alimentos & Proteína",
            description = "Maior processadora e exportadora de proteína animal do mundo em faturamento.",
            price = "R$ 36,40",
            changePercent = "+1.80%",
            isPositive = true,
            changeValue = "+R$ 0,64",
            dailyHigh = "R$ 36,90",
            dailyLow = "R$ 35,80",
            volume = "16,7M",
            marketCap = "R$ 80B",
            peRatio = "9.8x",
            dividendYield = "4.9%",
            high52w = "R$ 38,10",
            low52w = "R$ 21,30"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:EMBR3",
            ticker = "EMBR3",
            name = "Embraer ON",
            sector = "Aeroespacial & Defesa",
            description = "Terceira maior fabricante mundial de aeronaves comerciais e jatos executivos com forte carteira de pedidos.",
            price = "R$ 49,80",
            changePercent = "+3.20%",
            isPositive = true,
            changeValue = "+R$ 1,54",
            dailyHigh = "R$ 50,40",
            dailyLow = "R$ 48,60",
            volume = "18,9M",
            marketCap = "R$ 36B",
            peRatio = "24.2x",
            dividendYield = "1.2%",
            high52w = "R$ 52,00",
            low52w = "R$ 19,80"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:PRIO3",
            ticker = "PRIO3",
            name = "PRIO ON",
            sector = "Petróleo Independente",
            description = "Maior petroleira independente brasileira especializada em revitalização e eficiência de campos maduros.",
            price = "R$ 45,90",
            changePercent = "+1.10%",
            isPositive = true,
            changeValue = "+R$ 0,50",
            dailyHigh = "R$ 46,50",
            dailyLow = "R$ 45,20",
            volume = "9,8M",
            marketCap = "R$ 40B",
            peRatio = "6.8x",
            dividendYield = "2.1%",
            high52w = "R$ 52,80",
            low52w = "R$ 39,20"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:GGBR4",
            ticker = "GGBR4",
            name = "Gerdau PN",
            sector = "Siderurgia & Aço",
            description = "Maior produtora brasileira de aços longos e uma das principais fornecedoras para a construção civil das Américas.",
            price = "R$ 19,30",
            changePercent = "-0.40%",
            isPositive = false,
            changeValue = "-R$ 0,08",
            dailyHigh = "R$ 19,65",
            dailyLow = "R$ 19,15",
            volume = "12,1M",
            marketCap = "R$ 33B",
            peRatio = "6.1x",
            dividendYield = "6.8%",
            high52w = "R$ 24,10",
            low52w = "R$ 17,90"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:RADL3",
            ticker = "RADL3",
            name = "Raia Drogasil ON",
            sector = "Saúde & Farmácias",
            description = "Líder absoluta do varejo farmacêutico brasileiro, controladora das redes Droga Raia e Drogasil.",
            price = "R$ 26,10",
            changePercent = "+0.25%",
            isPositive = true,
            changeValue = "+R$ 0,07",
            dailyHigh = "R$ 26,45",
            dailyLow = "R$ 25,90",
            volume = "8,7M",
            marketCap = "R$ 43B",
            peRatio = "32.1x",
            dividendYield = "1.5%",
            high52w = "R$ 29,80",
            low52w = "R$ 24,10"
        ),
        BrazilianStock(
            symbol = "BMFBOVESPA:MGLU3",
            ticker = "MGLU3",
            name = "Magazine Luiza ON",
            sector = "Varejo & E-commerce",
            description = "Uma das maiores redes de varejo multicanal e marketplace do Brasil.",
            price = "R$ 9,85",
            changePercent = "+2.60%",
            isPositive = true,
            changeValue = "+R$ 0,25",
            dailyHigh = "R$ 10,20",
            dailyLow = "R$ 9,60",
            volume = "42,3M",
            marketCap = "R$ 7B",
            peRatio = "18.5x",
            dividendYield = "0.0%",
            high52w = "R$ 16,80",
            low52w = "R$ 8,10"
        )
    )

    val allAssets = benchmarkIndices + topStocks

    fun getTickerTapeString(): String {
        return "BMFBOVESPA:IBOV,BMFBOVESPA:PETR4,BMFBOVESPA:VALE3,BMFBOVESPA:ITUB4,BMFBOVESPA:BBDC4,BMFBOVESPA:BBAS3,BMFBOVESPA:ABEV3,BMFBOVESPA:WEGE3,BMFBOVESPA:B3SA3,BMFBOVESPA:RENT3,BMFBOVESPA:SUZB3,BMFBOVESPA:JBSS3,BMFBOVESPA:EMBR3,BMFBOVESPA:PRIO3,FX_IDC:USDBRL"
    }

    fun getWatchlistArrayJson(): String {
        return """["BMFBOVESPA:IBOV","BMFBOVESPA:PETR4","BMFBOVESPA:VALE3","BMFBOVESPA:ITUB4","BMFBOVESPA:BBDC4","BMFBOVESPA:BBAS3","BMFBOVESPA:ABEV3","BMFBOVESPA:WEGE3","BMFBOVESPA:RENT3","BMFBOVESPA:B3SA3","BMFBOVESPA:SUZB3","BMFBOVESPA:JBSS3","BMFBOVESPA:EMBR3","BMFBOVESPA:PRIO3","FX_IDC:USDBRL"]"""
    }

    fun findStock(symbolOrTicker: String): BrazilianStock? {
        val clean = symbolOrTicker.trim().uppercase()
        return allAssets.find { 
            it.symbol.equals(clean, ignoreCase = true) || 
            it.ticker.equals(clean, ignoreCase = true) ||
            it.symbol.endsWith(":$clean", ignoreCase = true)
        }
    }
}
